package com.acclivousbyte.bassam.models.genrelModels

data class Children(
    val alive: String,
    val city: String,
    val country: String,
    val credentials_issued: String,
    val credentials_revoked: String,
    val dob: String,
    val dob_calendar_type: String,
    val education: List<Any>,
    val gender: String,
    val id: Int,
    val m_father_name: String,
    val m_grand_father_name: String,
    val mother_name: String,
    val name: String,
    val nodeID: String,
    val p_dob: String,
    val p_education: String,
    val p_email: String,
    val p_landline: String,
    val p_location: String,
    val p_mobile: String,
    val p_mother_info: String,
    val p_profile_picture: String,
    val p_socialnetworks: String,
    val p_wife_info: String,
    val p_workplace: String,
    val parent_id: String,
    val profile_picture_circle: String,
    val profile_picture_square: String,
    val sequence: String
)